import SidebarComponents from '@/components/Sidebar.component'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import 'tailwindcss/tailwind.css'
// import './globals.css';
// import "./../assets/style.css";
import "./../styles/globals.css";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'E-Office',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className='flex gap-3 mt-4 px-4'>
          <div className='w-96 bg-white h-screen text-cyan-800'>
            <SidebarComponents />
          </div>x
          <div className='bg-red-100 w-full text-black mt-1'>{children}</div>
        </div>
      </body>
    </html>
  )
}
